[project]
name = 'Temporal-Paradox-Resolution-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.causal-consistency-integration]
path = 'contracts/causal-consistency-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.paradox-resolution-token]
path = 'contracts/paradox-resolution-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.temporal-anomaly-management]
path = 'contracts/temporal-anomaly-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.temporal-event-nft]
path = 'contracts/temporal-event-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
